# Generated by Django 3.2.10 on 2022-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0006_auto_20220324_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-04-13 12:54:06'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-04-13 12:54:06'),
        ),
        migrations.AlterField(
            model_name='mofarmmodelmodulerelations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-04-13 12:54:06'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-04-13 12:54:06', verbose_name='更新时间'),
        ),
    ]
