# Generated by Django 3.0.5 on 2022-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 11:47:56'),
        ),
        migrations.AddField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 11:47:56', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 11:47:56'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 11:47:56'),
        ),
        migrations.AlterField(
            model_name='mofarmotherdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 11:47:56'),
        ),
        migrations.AlterField(
            model_name='mofarmotherdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 11:47:56', verbose_name='更新时间'),
        ),
    ]
