# Generated by Django 3.0.5 on 2022-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0003_auto_20220316_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mofarmprojectstatus',
            old_name='run_history_msg',
            new_name='run_history_path',
        ),
        migrations.RenameField(
            model_name='mofarmprojectstatus',
            old_name='desc',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='mofarmprojectstatus',
            old_name='process',
            new_name='total_progress',
        ),
        migrations.AddField(
            model_name='mofarmproject',
            name='project_type',
            field=models.CharField(default='', max_length=100, verbose_name='所属算法类型（目标识别/图片分类/数据预测/异常检测）'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 14:16:04'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 14:16:04'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 14:16:04'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='status',
            field=models.CharField(default='', max_length=1000, verbose_name='运行状态:未运行/训练/测试'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 14:16:04', verbose_name='更新时间'),
        ),
    ]
