# Generated by Django 3.0.5 on 2022-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0004_auto_20220316_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mofarmprojectstatus',
            old_name='projectsetname',
            new_name='projectname',
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-03-23 15:19:52'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-23 15:19:52'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-03-23 15:19:52'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-23 15:19:52', verbose_name='更新时间'),
        ),
    ]
