# Generated by Django 3.2.10 on 2022-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0007_auto_20220413_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='mofarmmodel',
            name='module_id',
            field=models.IntegerField(default=-1, verbose_name='模块ID'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-04-14 11:26:17'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-04-14 11:26:17'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-04-14 11:26:17'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-04-14 11:26:17', verbose_name='更新时间'),
        ),
    ]
