# Generated by Django 3.0.5 on 2022-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoFarmDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='说明')),
                ('dataset_path', models.CharField(default='', max_length=200, verbose_name='CSV路径')),
                ('type', models.CharField(default='', max_length=100, verbose_name='数据集类型')),
                ('created_time', models.DateTimeField(default='2022-03-15 14:23:39')),
                ('updated_time', models.DateTimeField(default='2022-03-15 14:23:39')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmImagesDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetname', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('image_name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('image_md5', models.CharField(max_length=256, verbose_name='图片的md5')),
                ('tag_status', models.CharField(default='0', max_length=1, verbose_name='标注状态,0 未标注  1已标注')),
                ('image_size', models.CharField(max_length=32, verbose_name='图片宽高 :(宽,高)')),
                ('image_type', models.CharField(max_length=10, verbose_name='图片文件类型:jpg/png/tif')),
                ('label_msg', models.TextField(verbose_name='图片标注信息')),
                ('ratio', models.FloatField(max_length=20, verbose_name='图片缩放比例')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='模型名称')),
                ('moduleid', models.IntegerField(default=0, verbose_name='对应模块ID')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='说明')),
                ('model_path', models.CharField(default='', max_length=200, verbose_name='pth文件的路径')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmModelModuleRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(verbose_name='模块ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('model_id', models.IntegerField(verbose_name='模型ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='说明')),
                ('type', models.CharField(default='', max_length=100, verbose_name='模块的类型')),
                ('module_path', models.CharField(default='', max_length=200, verbose_name='模块的jason文件路径')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmOtherDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetname', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('file_path', models.CharField(max_length=128, verbose_name='具体文件路径')),
                ('created_time', models.DateTimeField(default='2022-03-15 14:23:39')),
                ('updated_time', models.DateTimeField(default='2022-03-15 14:23:39', verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='说明')),
                ('config_path', models.CharField(default='', max_length=200, verbose_name='配置jason文件路径')),
                ('status', models.CharField(default='', max_length=1000, verbose_name='运行状态')),
            ],
        ),
        migrations.CreateModel(
            name='MoFarmProjectStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('projectsetname', models.CharField(max_length=100, verbose_name='项目方案名称')),
                ('desc', models.CharField(max_length=100, verbose_name='运行状态说明(未运行/训练/测试)')),
                ('process', models.CharField(max_length=100, verbose_name='运行总进度')),
                ('run_real_time_msg', models.CharField(max_length=100, verbose_name='当前运行轮次的指标信息')),
                ('run_history_msg', models.CharField(max_length=100, verbose_name='运行状态历史信息json文件路径')),
            ],
        ),
    ]
