# Generated by Django 3.0.5 on 2022-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0002_auto_20220316_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoFarmOtherDataset',
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 14:09:03'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 14:09:03'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-03-16 14:09:03'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-03-16 14:09:03', verbose_name='更新时间'),
        ),
    ]
