# Generated by Django 3.2.10 on 2022-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoFarmBackEnd', '0009_auto_20220414_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mofarmdataset',
            name='created_time',
            field=models.DateTimeField(default='2022-04-14 12:03:11'),
        ),
        migrations.AlterField(
            model_name='mofarmdataset',
            name='updated_time',
            field=models.DateTimeField(default='2022-04-14 12:03:11'),
        ),
        migrations.AlterField(
            model_name='mofarmmodel',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='created_time',
            field=models.DateTimeField(default='2022-04-14 12:03:11'),
        ),
        migrations.AlterField(
            model_name='mofarmproject',
            name='updated_time',
            field=models.DateTimeField(default='2022-04-14 12:03:11', verbose_name='更新时间'),
        ),
    ]
